SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE comments;
TRUNCATE TABLE posts;

ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;
ALTER TABLE posts ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;